### ISSUE TITLE
Add prebuilt APKs

### ISSUE THREAD

**Issue by rayzchen** [kivy/kivy-launcher#14]
Could someone create a place to store some APKs built? Some people can't build it themselves and I was just hoping to install an APK instead of building one then installing it.

**Comment by xloem** [comment]
Until there's an official channel, could someone upload one to a free service like https://siasky.net/ ?

**Comment by xloem** [comment]
I'm noting that the project is set up to build apks during continuous integration: https://github.com/kivy/kivy-launcher/blob/master/.circleci/config.yml these could probably be built and published somehow on github's servers, either as releases or committed to a branch as binary data.

**Comment by xloem** [comment]
Here's the current binary: https://siasky.net/AAD8kvNFZBwNjFZCx8-vkh1RvXjRKptW8WZj9k911DseaQ/launcher-0.1-armeabi-v7a-debug.apk .  I forked the repo and linked to circleci, and the app artifact built.  I ssh'd into the circleci build to upload it.

**Comment by clach04** [comment]
Recent ci build https://github.com/kivy/kivy-launcher/actions/runs/1643252250

**Comment by chrysn** [comment]
Currently, the latest built APK can be reached by going to this project's [actions](https://github.com/kivy/kivy-launcher/actions), selecting the top-most CI action, and downloading the "package" artifact on the bottom. Note that you need to be logged in to GitHub to do this -- otherwise, the "package" text is not a link (without any hint as to what is going on). The downloaded `package.zip` contains a `launcher-0.1-...-debug.apk` file that can be installed by opening it on an Android device.

**Comment by rayzchen** [comment]
Seems like this is resolved then.

**Comment by RigacciOrg** [comment]
The latest CI have failed (red dot). The last one that worked (April 2023) has the artifact package exired, so there is nothing to download.
